### ISSUE TITLE
License for source code and data

### ISSUE THREAD

**Issue by johnjohndoe** [CodeforKarlsruhe/wo-ist-markt#12]
I noticed that the project is missing a license. I suggest you add a _LICENSE.txt_ file for the source code. It might however be necessary to declare a separate license for the market data itself. In terms of market data for Berlin (which I have almost ready to add) the separate license is needed - I will prepare this in a separate pull request.

**Comment by torfsen** [comment]
Good catch. I've added a license file. We're using MIT for all our projects, I hope that's OK with you. I've added a note that the license only holds unless noted otherwise, so adding the Berlin data under another (compatible) license won't be a problem (and our 3rd-party libraries also have their own license comments).

**Comment by johnjohndoe** [comment]
Fine.
