### ISSUE TITLE
Some Berlin markets has wrong geopositions

### ISSUE THREAD

**Issue by tursics** [CodeforKarlsruhe/wo-ist-markt#16]
The 'Antik- und Buchmarkt am Bodemuseum Am Kupfergraben/ Museumsinsel' is located at the Bodemuseum and not at the new Stadtschloss. And the 'design.Börse_Berlin in Galeria Kaufhof am Ostbahnhof, Erich-Steinfurth-Straße' is in Berlin and not in Finowfurt/Brandenburg.

**Comment by johnjohndoe** [comment]
@tursics I am not sure we can handle content issues here. Instead these request should be [addressed at the data origin](http://daten.berlin.de/datensaetze/wochen-und-tr%C3%B6delm%C3%A4rkte).

@torfsen I suggest you **close** the issues section for this repository since we should collect all issues [here](https://github.com/wo-ist-markt/wo-ist-markt.github.io/issues). @tursics Please use the other issues section for future entries.
